/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Configuracion.Conexion;
import Modelo.Registrar_Estudiante;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CATA
 */
public class Entrada extends javax.swing.JFrame {

    String numeDocumento;
    Connection coneccion;
    Conexion conexionbasededatos = new Conexion();

    public Entrada() {
        initComponents();
        
        ImageIcon iconosaliregistro = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconocasa.png");
        btnsalirregistro.setIcon(iconosaliregistro);
    }

    public Registrar_Estudiante buscarporCedula(String numerodocumento) {

        Registrar_Estudiante registroEstudiante = new Registrar_Estudiante();

        coneccion = conexionbasededatos.getconeccionbasedatos();
        PreparedStatement ps = null;
        ResultSet rs = null;

        String sql = "select * from Registrar_Estudiante where numeDocumento=?";

        try {
            ps = coneccion.prepareStatement(sql);
            ps.setString(1, numerodocumento);
            rs = ps.executeQuery();
            while (rs.next()) {
                registroEstudiante.setId_estudiante(rs.getInt(1));
                registroEstudiante.setNumeDocumento(rs.getString(5));
                registroEstudiante.setNomEstudiante(rs.getString(2));
                registroEstudiante.setApeEstudiante(rs.getString(3));
                registroEstudiante.setGrado(rs.getString(7));
                registroEstudiante.setEstado(rs.getString(9));
                registroEstudiante.setTipoBeneficio(rs.getString(8));

                return registroEstudiante;
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        return registroEstudiante;

    }

    
    
    
    public void mostrarfoto(String numeroDocumentoestudiante){
        
        String ruta = "src\\main\\java\\fotos\\"+numeroDocumentoestudiante+".jpg";
        ImageIcon foto = new ImageIcon(ruta);
        lbimagen.setIcon(foto);
         
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnumdocu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JLabel();
        txtnombres = new javax.swing.JLabel();
        txtgrado = new javax.swing.JLabel();
        txtestado = new javax.swing.JLabel();
        txtbeneficio = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        lbimagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnsalirregistro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtregistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("N°Documento:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 89, -1));

        jLabel2.setText("NOMBRES:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel3.setText("APELLIDOS:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel4.setText("GRADO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel5.setText("ESTADO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        txtnumdocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumdocuActionPerformed(evt);
            }
        });
        jPanel1.add(txtnumdocu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 174, -1));

        jLabel6.setText("BENEFICIO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));
        jPanel1.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 174, 20));
        jPanel1.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 174, 20));
        jPanel1.add(txtgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 174, 22));
        jPanel1.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 117, 22));
        jPanel1.add(txtbeneficio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 117, 21));

        btnRegistro.setText("Consultar");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));
        jPanel1.add(lbimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 230, 308));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsalirregistro, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsalirregistro, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 390, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        txtregistro.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtregistro.setText("REGISTRO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(txtregistro)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtregistro)
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 640, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumdocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumdocuActionPerformed


    }//GEN-LAST:event_txtnumdocuActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed

        String numeDocumento = txtnumdocu.getText();

        Registrar_Estudiante Resultado = buscarporCedula(numeDocumento);
        
        

        if (Resultado.getNumeDocumento().equals(numeDocumento)) {
            txtnombres.setText(Resultado.getNomEstudiante());
            txtapellidos.setText(Resultado.getApeEstudiante());
            txtgrado.setText(Resultado.getGrado());
            txtestado.setText(Resultado.getEstado());
            txtbeneficio.setText(Resultado.getTipoBeneficio());
            
            
            mostrarfoto(numeDocumento);
            
            
            
        } else {
            txtnombres.setText("");
            txtapellidos.setText("");
            txtgrado.setText("");
            txtestado.setText("");
        }
        if (Resultado.getNumeDocumento().equals(numeDocumento)) {
            JOptionPane.showMessageDialog(null, "Registro");
            txtnumdocu.setText("");
            txtnombres.setText("");
            txtapellidos.setText("");
            txtgrado.setText("");
            txtestado.setText("");
            txtbeneficio.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Error Registro");
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        Panel_Principal panel_Principal = new Panel_Principal();
        panel_Principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel btnsalirregistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbimagen;
    private javax.swing.JLabel txtapellidos;
    private javax.swing.JLabel txtbeneficio;
    private javax.swing.JLabel txtestado;
    private javax.swing.JLabel txtgrado;
    private javax.swing.JLabel txtnombres;
    private javax.swing.JTextField txtnumdocu;
    private javax.swing.JLabel txtregistro;
    // End of variables declaration//GEN-END:variables
}
