/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author PC-01
 */
public class Panel_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Panel_Principal
     */
    public Panel_Principal() {
        initComponents();
        ImageIcon icon = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconocasa.png");
        jLabel2.setIcon(icon);
        
        ImageIcon iconoestudiante = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoestudiantes.png");
        logoestudiante.setIcon(iconoestudiante);
        
        ImageIcon iconoregistro = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoregistro.png");
        logoregistro.setIcon(iconoregistro);
        
        ImageIcon iconosalir = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconocerrar.png");
        btnsalir.setIcon(iconosalir);
        
        ImageIcon iconoinforme = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconodashboard.png");
        logoinforme.setIcon(iconoinforme);
        
        ImageIcon iconoagregarestudiante = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoestudiante.png");
        logoagregarestudiante.setIcon(iconoagregarestudiante);
        
        ImageIcon iconoagregarestudiante3 = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoestudiante.png");
        logoagregarestudiante3.setIcon(iconoagregarestudiante3);
        
        ImageIcon iconoagregarestudiante2 = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoestudiante.png");
        logoagregarestudiante2.setIcon(iconoagregarestudiante2);
        
        ImageIcon iconoagregarestudiante4 = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoestudiante.png");
        logoagregarestudiante4.setIcon(iconoagregarestudiante4);
        
        ImageIcon iconoeliminar = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoeliminar.png");
        logoeliminar.setIcon(iconoeliminar);
        
        ImageIcon iconoagregar = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoagregar.png");
        logoagregar.setIcon(iconoagregar);
        
        ImageIcon iconoactualizar = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoactualizar.png");
        logoactualizar.setIcon(iconoactualizar);
        
        ImageIcon iconoagregarregistro = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoinspeccion.png");
        logoagregarregistro.setIcon(iconoagregarregistro);
        
        ImageIcon iconoactualizarregistro = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoinspeccion.png");
        logoagregarregistro1.setIcon(iconoactualizarregistro);
        
        ImageIcon iconoeliminarregistro = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoinspeccion.png");
        logoagregarregistro2.setIcon(iconoeliminarregistro);
        
        ImageIcon iconoregistrototal = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoinspeccion.png");
        logoagregarregistro3.setIcon(iconoregistrototal);
        
        ImageIcon iconoeliminar1 = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoeliminar.png");
        logoeliminar1.setIcon(iconoeliminar1);
        
        ImageIcon iconoagregar1 = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoagregar.png");
        logoagregar1.setIcon(iconoagregar1);
        
        ImageIcon iconoactualizar1 = new ImageIcon("C:/Users/PC-01/Documents/NetBeansProjects/Restaurante_Escolar/src/main/java/img/iconoactualizar.png");
        logoactualizar1.setIcon(iconoactualizar1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelprincipal = new javax.swing.JPanel();
        panellateral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnestudiantes = new javax.swing.JPanel();
        logoestudiante = new javax.swing.JLabel();
        txtestudiantes = new javax.swing.JLabel();
        btnregistro = new javax.swing.JPanel();
        logoregistro = new javax.swing.JLabel();
        txtregistro1 = new javax.swing.JLabel();
        btndashboard = new javax.swing.JPanel();
        logoinforme = new javax.swing.JLabel();
        txtinforme = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JLabel();
        panelcentral = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        actualizarestudiante = new javax.swing.JPanel();
        logoagregarestudiante = new javax.swing.JLabel();
        txtactualizarestudiante = new javax.swing.JLabel();
        logoactualizar = new javax.swing.JLabel();
        agregarestudainte = new javax.swing.JPanel();
        logoagregarestudiante2 = new javax.swing.JLabel();
        txtagregarestudiante2 = new javax.swing.JLabel();
        logoagregar = new javax.swing.JLabel();
        eliminarestudante = new javax.swing.JPanel();
        logoagregarestudiante3 = new javax.swing.JLabel();
        txtagregarestudiante3 = new javax.swing.JLabel();
        logoeliminar = new javax.swing.JLabel();
        reporteestudainte = new javax.swing.JPanel();
        logoagregarestudiante4 = new javax.swing.JLabel();
        txtagregarestudiante4 = new javax.swing.JLabel();
        agregarregistro = new javax.swing.JPanel();
        logoagregarregistro = new javax.swing.JLabel();
        txtagregarregistro = new javax.swing.JLabel();
        logoagregar1 = new javax.swing.JLabel();
        eliminarregistro = new javax.swing.JPanel();
        logoagregarregistro2 = new javax.swing.JLabel();
        txtagregarregistro2 = new javax.swing.JLabel();
        logoeliminar1 = new javax.swing.JLabel();
        registrototal = new javax.swing.JPanel();
        logoagregarregistro3 = new javax.swing.JLabel();
        txtagregarestudiante7 = new javax.swing.JLabel();
        txtseccionregistros = new javax.swing.JLabel();
        actualizarregistro = new javax.swing.JPanel();
        logoagregarregistro1 = new javax.swing.JLabel();
        txtactualizarregistro = new javax.swing.JLabel();
        logoactualizar1 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        p3 = new javax.swing.JPanel();
        p4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panelprincipal.setBackground(new java.awt.Color(255, 255, 255));
        Panelprincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        Panelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panellateral.setBackground(new java.awt.Color(0, 0, 0));
        panellateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panellateral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 5, 120, 90));

        btnestudiantes.setBackground(new java.awt.Color(102, 102, 102));
        btnestudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnestudiantesMouseClicked(evt);
            }
        });
        btnestudiantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnestudiantes.add(logoestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 90));

        txtestudiantes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtestudiantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtestudiantes.setText("ESTUDIANTES");
        btnestudiantes.add(txtestudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        panellateral.add(btnestudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 100, 124, 120));

        btnregistro.setBackground(new java.awt.Color(102, 102, 102));
        btnregistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistroMouseClicked(evt);
            }
        });
        btnregistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoregistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnregistro.add(logoregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 90));

        txtregistro1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtregistro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtregistro1.setText("REGISTRO");
        btnregistro.add(txtregistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        panellateral.add(btnregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 220, 124, 120));

        btndashboard.setBackground(new java.awt.Color(102, 102, 102));
        btndashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndashboardMouseClicked(evt);
            }
        });
        btndashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoinforme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoinformeMouseClicked(evt);
            }
        });
        btndashboard.add(logoinforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 90));

        txtinforme.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtinforme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtinforme.setText("DASHBOARD");
        btndashboard.add(txtinforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        panellateral.add(btndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 340, 124, 120));

        Panelprincipal.add(panellateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 600));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Colegio Oficial Nuestra Señora del Rosario");

        btnsalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        Panelprincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 770, 100));

        panelcentral.setLayout(new java.awt.CardLayout());

        p1.setBackground(new java.awt.Color(204, 204, 204));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bienvenido al SR del Restaurante");
        p1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));
        p1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 82, 789, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Sección de estudiantes");
        p1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 98, -1, -1));

        txtactualizarestudiante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtactualizarestudiante.setForeground(new java.awt.Color(51, 102, 0));
        txtactualizarestudiante.setText("Actualizar Estudiante");

        javax.swing.GroupLayout actualizarestudianteLayout = new javax.swing.GroupLayout(actualizarestudiante);
        actualizarestudiante.setLayout(actualizarestudianteLayout);
        actualizarestudianteLayout.setHorizontalGroup(
            actualizarestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarestudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actualizarestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actualizarestudianteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtactualizarestudiante)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(actualizarestudianteLayout.createSequentialGroup()
                        .addComponent(logoagregarestudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoactualizar)
                        .addGap(26, 26, 26))))
        );
        actualizarestudianteLayout.setVerticalGroup(
            actualizarestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarestudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actualizarestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoagregarestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoactualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtactualizarestudiante)
                .addContainerGap())
        );

        p1.add(actualizarestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 136, -1, -1));

        txtagregarestudiante2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtagregarestudiante2.setForeground(new java.awt.Color(51, 102, 0));
        txtagregarestudiante2.setText("Agregar Estudiante");

        javax.swing.GroupLayout agregarestudainteLayout = new javax.swing.GroupLayout(agregarestudainte);
        agregarestudainte.setLayout(agregarestudainteLayout);
        agregarestudainteLayout.setHorizontalGroup(
            agregarestudainteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarestudainteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agregarestudainteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarestudainteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtagregarestudiante2)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(agregarestudainteLayout.createSequentialGroup()
                        .addComponent(logoagregarestudiante2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(logoagregar)
                        .addGap(24, 24, 24))))
        );
        agregarestudainteLayout.setVerticalGroup(
            agregarestudainteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarestudainteLayout.createSequentialGroup()
                .addGroup(agregarestudainteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarestudainteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoagregarestudiante2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarestudainteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoagregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(txtagregarestudiante2)
                .addContainerGap())
        );

        p1.add(agregarestudainte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 136, -1, -1));

        txtagregarestudiante3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtagregarestudiante3.setForeground(new java.awt.Color(255, 0, 0));
        txtagregarestudiante3.setText("Eliminar Estudiante");

        javax.swing.GroupLayout eliminarestudanteLayout = new javax.swing.GroupLayout(eliminarestudante);
        eliminarestudante.setLayout(eliminarestudanteLayout);
        eliminarestudanteLayout.setHorizontalGroup(
            eliminarestudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarestudanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eliminarestudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarestudanteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtagregarestudiante3)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(eliminarestudanteLayout.createSequentialGroup()
                        .addComponent(logoagregarestudiante3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoeliminar)
                        .addGap(34, 34, 34))))
        );
        eliminarestudanteLayout.setVerticalGroup(
            eliminarestudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarestudanteLayout.createSequentialGroup()
                .addGroup(eliminarestudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarestudanteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoagregarestudiante3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarestudanteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoeliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(txtagregarestudiante3)
                .addContainerGap())
        );

        p1.add(eliminarestudante, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 136, -1, -1));

        txtagregarestudiante4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtagregarestudiante4.setForeground(new java.awt.Color(102, 102, 102));
        txtagregarestudiante4.setText("Reporte Estudiante");

        javax.swing.GroupLayout reporteestudainteLayout = new javax.swing.GroupLayout(reporteestudainte);
        reporteestudainte.setLayout(reporteestudainteLayout);
        reporteestudainteLayout.setHorizontalGroup(
            reporteestudainteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteestudainteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reporteestudainteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reporteestudainteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtagregarestudiante4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(reporteestudainteLayout.createSequentialGroup()
                        .addComponent(logoagregarestudiante4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        reporteestudainteLayout.setVerticalGroup(
            reporteestudainteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteestudainteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoagregarestudiante4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtagregarestudiante4)
                .addContainerGap())
        );

        p1.add(reporteestudainte, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 136, -1, -1));

        txtagregarregistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtagregarregistro.setForeground(new java.awt.Color(51, 102, 0));
        txtagregarregistro.setText("Agregar Registro");

        javax.swing.GroupLayout agregarregistroLayout = new javax.swing.GroupLayout(agregarregistro);
        agregarregistro.setLayout(agregarregistroLayout);
        agregarregistroLayout.setHorizontalGroup(
            agregarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarregistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agregarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarregistroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtagregarregistro)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(agregarregistroLayout.createSequentialGroup()
                        .addComponent(logoagregarregistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(logoagregar1)
                        .addGap(24, 24, 24))))
        );
        agregarregistroLayout.setVerticalGroup(
            agregarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarregistroLayout.createSequentialGroup()
                .addGroup(agregarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarregistroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoagregarregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarregistroLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoagregar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(txtagregarregistro)
                .addContainerGap())
        );

        p1.add(agregarregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 327, -1, -1));

        txtagregarregistro2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtagregarregistro2.setForeground(new java.awt.Color(255, 0, 0));
        txtagregarregistro2.setText("Eliminar Registro");

        javax.swing.GroupLayout eliminarregistroLayout = new javax.swing.GroupLayout(eliminarregistro);
        eliminarregistro.setLayout(eliminarregistroLayout);
        eliminarregistroLayout.setHorizontalGroup(
            eliminarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarregistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eliminarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarregistroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtagregarregistro2)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(eliminarregistroLayout.createSequentialGroup()
                        .addComponent(logoagregarregistro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoeliminar1)
                        .addGap(34, 34, 34))))
        );
        eliminarregistroLayout.setVerticalGroup(
            eliminarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarregistroLayout.createSequentialGroup()
                .addGroup(eliminarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarregistroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoagregarregistro2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarregistroLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoeliminar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(txtagregarregistro2)
                .addContainerGap())
        );

        p1.add(eliminarregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 327, -1, -1));

        txtagregarestudiante7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtagregarestudiante7.setForeground(new java.awt.Color(102, 102, 102));
        txtagregarestudiante7.setText("Registro Total");

        javax.swing.GroupLayout registrototalLayout = new javax.swing.GroupLayout(registrototal);
        registrototal.setLayout(registrototalLayout);
        registrototalLayout.setHorizontalGroup(
            registrototalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrototalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrototalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrototalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtagregarestudiante7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registrototalLayout.createSequentialGroup()
                        .addComponent(logoagregarregistro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        registrototalLayout.setVerticalGroup(
            registrototalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrototalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoagregarregistro3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtagregarestudiante7)
                .addContainerGap())
        );

        p1.add(registrototal, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 327, -1, -1));

        txtseccionregistros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtseccionregistros.setText("Sección de registros");
        p1.add(txtseccionregistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 289, -1, -1));

        txtactualizarregistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtactualizarregistro.setForeground(new java.awt.Color(51, 102, 0));
        txtactualizarregistro.setText("Actualizar Registro");

        javax.swing.GroupLayout actualizarregistroLayout = new javax.swing.GroupLayout(actualizarregistro);
        actualizarregistro.setLayout(actualizarregistroLayout);
        actualizarregistroLayout.setHorizontalGroup(
            actualizarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarregistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actualizarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actualizarregistroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtactualizarregistro)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(actualizarregistroLayout.createSequentialGroup()
                        .addComponent(logoagregarregistro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoactualizar1)
                        .addGap(26, 26, 26))))
        );
        actualizarregistroLayout.setVerticalGroup(
            actualizarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarregistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actualizarregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoagregarregistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoactualizar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtactualizarregistro)
                .addContainerGap())
        );

        p1.add(actualizarregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 327, -1, -1));

        panelcentral.add(p1, "card2");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        panelcentral.add(p2, "card3");

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        panelcentral.add(p3, "card4");

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        panelcentral.add(p4, "card5");

        Panelprincipal.add(panelcentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 770, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onClick(JPanel panel){
        panel.setBackground(new Color(120,120,120));
    }
    
    private void onleaveClick(JPanel panel){
        panel.setBackground(new Color(102,102,102));
    }
    
    private void btnsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseClicked
        dispose();
    }//GEN-LAST:event_btnsalirMouseClicked

    private void logoinformeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoinformeMouseClicked
        onClick(btndashboard);
        onleaveClick(btnestudiantes);
        onleaveClick(btnregistro);
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_logoinformeMouseClicked

    private void btndashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashboardMouseClicked
        
        onClick(btndashboard);
        onleaveClick(btnestudiantes);
        onleaveClick(btnregistro);
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_btndashboardMouseClicked

    private void btnregistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistroMouseClicked
        onClick(btnregistro);
        onleaveClick(btnestudiantes);
        onleaveClick(btndashboard);
        
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_btnregistroMouseClicked

    private void btnestudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnestudiantesMouseClicked
        onClick(btnestudiantes);
        onleaveClick(btndashboard);
        onleaveClick(btnregistro);
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
    }//GEN-LAST:event_btnestudiantesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panelprincipal;
    private javax.swing.JPanel actualizarestudiante;
    private javax.swing.JPanel actualizarregistro;
    private javax.swing.JPanel agregarestudainte;
    private javax.swing.JPanel agregarregistro;
    private javax.swing.JPanel btndashboard;
    private javax.swing.JPanel btnestudiantes;
    private javax.swing.JPanel btnregistro;
    private javax.swing.JLabel btnsalir;
    private javax.swing.JPanel eliminarestudante;
    private javax.swing.JPanel eliminarregistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoactualizar;
    private javax.swing.JLabel logoactualizar1;
    private javax.swing.JLabel logoagregar;
    private javax.swing.JLabel logoagregar1;
    private javax.swing.JLabel logoagregarestudiante;
    private javax.swing.JLabel logoagregarestudiante2;
    private javax.swing.JLabel logoagregarestudiante3;
    private javax.swing.JLabel logoagregarestudiante4;
    private javax.swing.JLabel logoagregarregistro;
    private javax.swing.JLabel logoagregarregistro1;
    private javax.swing.JLabel logoagregarregistro2;
    private javax.swing.JLabel logoagregarregistro3;
    private javax.swing.JLabel logoeliminar;
    private javax.swing.JLabel logoeliminar1;
    private javax.swing.JLabel logoestudiante;
    private javax.swing.JLabel logoinforme;
    private javax.swing.JLabel logoregistro;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel panelcentral;
    private javax.swing.JPanel panellateral;
    private javax.swing.JPanel registrototal;
    private javax.swing.JPanel reporteestudainte;
    private javax.swing.JLabel txtactualizarestudiante;
    private javax.swing.JLabel txtactualizarregistro;
    private javax.swing.JLabel txtagregarestudiante2;
    private javax.swing.JLabel txtagregarestudiante3;
    private javax.swing.JLabel txtagregarestudiante4;
    private javax.swing.JLabel txtagregarestudiante7;
    private javax.swing.JLabel txtagregarregistro;
    private javax.swing.JLabel txtagregarregistro2;
    private javax.swing.JLabel txtestudiantes;
    private javax.swing.JLabel txtinforme;
    private javax.swing.JLabel txtregistro1;
    private javax.swing.JLabel txtseccionregistros;
    // End of variables declaration//GEN-END:variables
}
